/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZZZ_C_YPRODUCTObjectPageObjectPage journey");

        opaTest("Navigate to ZZZ_C_YPRODUCTObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheZZZ_C_YPRODUCTListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZZZ_C_YPRODUCTListGenerated.onTable().iCheckRows();
            When.onTheZZZ_C_YPRODUCTListGenerated.onTable().iPressRow(0);

            Then.onTheZZZ_C_YPRODUCTObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the GeneralInfo section of the Object Page", function (_Given, _When, Then) {
            Then.onTheZZZ_C_YPRODUCTObjectPageGenerated.iCheckSection({ section: "GeneralInfo" });
            Then.onTheZZZ_C_YPRODUCTObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Productid" });
            Then.onTheZZZ_C_YPRODUCTObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Productname" });
            Then.onTheZZZ_C_YPRODUCTObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Description" });
            Then.onTheZZZ_C_YPRODUCTObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Category" });
            Then.onTheZZZ_C_YPRODUCTObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Supplierid" });
            Then.onTheZZZ_C_YPRODUCTObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Suppliername" });
            Then.onTheZZZ_C_YPRODUCTObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Price" });
            Then.onTheZZZ_C_YPRODUCTObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Stockqty" });
            Then.onTheZZZ_C_YPRODUCTObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Status" });
            Then.onTheZZZ_C_YPRODUCTObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LocalLastChanged" });
            Then.onTheZZZ_C_YPRODUCTObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LastChanged" });
            Then.onTheZZZ_C_YPRODUCTObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CreatedBy" });
            Then.onTheZZZ_C_YPRODUCTObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CreatedAt" });
            Then.onTheZZZ_C_YPRODUCTObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "ChangedBy" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});